# Generated by Django 5.2 on 2025-07-14 10:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0005_remove_subscriptionplan_max_image_uploads_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
