# Generated by Django 5.2 on 2025-04-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qamodel',
            name='question',
            field=models.TextField(blank=True),
        ),
    ]
