# Generated by Django 5.2 on 2025-05-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_qamodel_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videomodel',
            name='thumbnail_url',
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='question',
            field=models.TextField(blank=True),
        ),
    ]
