# Generated by Django 5.2 on 2025-05-07 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_videomodel_thumbnail_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videomodel',
            name='courses',
        ),
        migrations.AddField(
            model_name='videomodel',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='app1.coursemodel'),
        ),
    ]
