# Generated by Django 5.2 on 2025-05-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_videomodel_courses_videomodel_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='course_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
