# Generated by Django 5.2 on 2025-05-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_coursemodel_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='course_name',
            field=models.CharField(max_length=255),
        ),
    ]
