# Generated by Django 5.2 on 2025-06-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_coursemodel_course_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_video_id', models.CharField(max_length=20, unique=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('transcript_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
