# Generated by Django 5.2 on 2025-07-13 08:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_transcriptmodel_transcript_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='youtube_video_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='videomodel',
            unique_together={('user', 'youtube_video_id')},
        ),
    ]
