# Generated by Django 5.2 on 2025-07-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_videomodel_youtube_video_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptmodel',
            name='youtube_video_id',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='youtube_video_id',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
