# Generated by Django 5.2 on 2025-07-15 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessionmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qamodel',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qas', to='app.sessionmodel'),
        ),
        migrations.AddField(
            model_name='notesmodel',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='app.sessionmodel'),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.sessionmodel'),
        ),
        migrations.AddField(
            model_name='bookmarkmodel',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='app.sessionmodel'),
        ),
        migrations.AddField(
            model_name='videomodel',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='app.coursemodel'),
        ),
        migrations.AddField(
            model_name='videomodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessionmodel',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='app.videomodel'),
        ),
        migrations.AlterUniqueTogether(
            name='coursemodel',
            unique_together={('course_name', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='bookmarkmodel',
            unique_together={('session', 'time_stamp')},
        ),
        migrations.AlterUniqueTogether(
            name='videomodel',
            unique_together={('user', 'youtube_video_id')},
        ),
        migrations.AlterUniqueTogether(
            name='sessionmodel',
            unique_together={('video', 'user')},
        ),
    ]
